server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:journaldb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

kafka:
  bootstrap-servers: localhost:9092

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN
